### 1. Подключение Google Диска

Эту ячейку нужно запустить один раз в начале работы, чтобы ваш Google Диск стал доступен в Colab.

Когда вы запустите эту ячейку, появится запрос на авторизацию. Следуйте инструкциям: выберите свой аккаунт Google, разрешите Colab доступ к Google Диску, а затем скопируйте и вставьте полученный код авторизации в поле ввода в Colab.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# После успешного подключения вы увидите сообщение: "Mounted at /content/drive"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### 2. Проверка содержимого Google Диска

После подключения Диска, вы можете проверить, какие файлы и папки доступны. Все файлы вашего Диска будут находиться по пути `/content/drive/MyDrive/`. Замените `Моя_Курсовая/Данные_CSV/` на путь к вашей папке на Диске.

In [ ]:
import os

# Замените этот путь на путь к вашей папке на Google Диске
data_folder_path = '/content/drive/MyDrive/КурсоваяСинтетическийКонтроль/dataFiles'

# Проверим, существует ли папка
if os.path.exists(data_folder_path):
    print(f"Содержимое папки '{data_folder_path}':")
    for filename in os.listdir(data_folder_path):
        print(filename)
else:
    print(f"Папка '{data_folder_path}' не найдена. Проверьте правильность пути и название папки на вашем Google Диске.")

Содержимое папки '/content/drive/MyDrive/КурсоваяСинтетическийКонтроль/dataFiles':
Table_of_Gross_Cigarette_Tax_Revenue_Per_State_(Orzechowski_and_Walker_Tax_Burden_on_Tobacco)_20260810.csv

### 3. Загрузка CSV-файла в DataFrame с помощью pandas

Теперь, когда вы убедились, что файл виден, можно загрузить его в pandas DataFrame. Замените `ваш_файл.csv` на имя вашего файла.

In [ ]:
import pandas as pd

# Замените 'ваш_файл.csv' на реальное имя вашего файла
csv_file_path = os.path.join(data_folder_path, 'USStatisticAges1.csv')

try:
    df = pd.read_csv(csv_file_path)
    print("Файл успешно загружен!")
    display(df.head())
except FileNotFoundError:
    print(f"Ошибка: Файл '{csv_file_path}' не найден. Убедитесь, что имя файла и путь указаны верно.")
except Exception as e:
    print(f"Произошла ошибка при загрузке файла: {e}")

Файл успешно загружен!

,Label (Grouping),Alabama!!Total population!!Number,Alabama!!Total population!!Percent,Alaska!!Total population!!Number,Alaska!!Total population!!Percent,Arizona!!Total population!!Number,Arizona!!Total population!!Percent,Arkansas!!Total population!!Number,Arkansas!!Total population!!Percent,California!!Total population!!Number,...,Washington!!Total population!!Number,Washington!!Total population!!Percent,West Virginia!!Total population!!Number,West Virginia!!Total population!!Percent,Wisconsin!!Total population!!Number,Wisconsin!!Total population!!Percent,Wyoming!!Total population!!Number,Wyoming!!Total population!!Percent,Puerto Rico!!Total population!!Number,Puerto Rico!!Total population!!Percent
0,15 to 19 years,"324,58",7.3,"50,094",8.0,"367,722",7.2,"198,765",7.4,"2,450,888",...,"427,968",7.3,"125,578",6.9,"407,195",7.6,"41,903",8.5,"313,436",8.2
1,20 to 24 years,"306,865",6.9,"39,892",6.4,"362,86",7.1,"181,598",6.8,"2,381,288",...,"390,185",6.6,"120,109",6.6,"357,292",6.7,"33,455",6.8,"301,191",7.9

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1785 entries, 0 to 1784
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   LocationAbbr     1785 non-null   object
 1   LocationDesc     1785 non-null   object
 2   Year             1785 non-null   int64
 3   Datasource       1785 non-null   object
 4   TopicDesc        1785 non-null   object
 5   MeasureDesc      1785 non-null   object
 6   Data_Value       1785 non-null   object
 7   Data_Value_Unit  1785 non-null   object
 8   Data_Value_Type  1785 non-null   object
 9   GeoLocation      1785 non-null   object
 10  Source           1785 non-null   object
 11  TopicTypeId      1785 non-null   object
 12  TopicId          1785 non-null   object
 13  MeasureId        1785 non-null   object
dtypes: int64(1), object(13)
memory usage: 195.4+ KB
None

### 4. Загрузка и предварительный анализ всех CSV-файлов

In [2]:
import os
import pandas as pd

# Define data_folder_path here to ensure it's available
data_folder_path = '/content/drive/MyDrive/КурсоваяСинтетическийКонтроль/dataFiles'

# Словарь для хранения всех загруженных DataFrame'ов
dfs = {}

# Получаем список всех файлов в папке
files_in_folder = os.listdir(data_folder_path)

# Фильтруем только CSV-файлы
csv_files = [f for f in files_in_folder if f.endswith('.csv')]

if not csv_files:
    print(f"В папке '{data_folder_path}' не найдено ни одного CSV-файла.")
else:
    print(f"Найдено {len(csv_files)} CSV-файлов. Загружаем...")
    for csv_file_name in csv_files:
        full_csv_path = os.path.join(data_folder_path, csv_file_name)
        print(f"\n--- Загрузка файла: {csv_file_name} ---")
        try:
            # Try reading with default settings first
            df_temp = pd.read_csv(full_csv_path)
        except Exception as e:
            print(f"Произошла ошибка при загрузке или обработке файла {csv_file_name}: {e}")
            # If default fails, try with common alternatives like semicolon delimiter and error handling
            print("Попытка загрузки с другим разделителем (';') или пропуском некорректных строк...")
            try:
                df_temp = pd.read_csv(full_csv_path, sep=';', on_bad_lines='skip') # Added sep=';' and on_bad_lines='skip'
                print("Загружено с альтернативными настройками.")
            except Exception as e_alt:
                print(f"Повторная ошибка при загрузке файла {csv_file_name} с альтернативными настройками: {e_alt}")
                continue # Skip to the next file if even alternative fails

        dfs[csv_file_name] = df_temp # Сохраняем DataFrame в словаре
        print("Файл успешно загружен!")
        print("Первые 5 строк:")
        display(df_temp.head())
        print("Информация о столбцах:")
        df_temp.info()

Найдено 5 CSV-файлов. Загружаем...

--- Загрузка файла: The_Tax_Burden_on_Tobacco,_1970-2019_20260811.csv ---
Файл успешно загружен!
Первые 5 строк:

,LocationAbbr,LocationDesc,Year,Datasource,TopicDesc,MeasureDesc,SubMeasureDesc,Data_Value,Data_Value_Unit,Data_Value_Type,GeoLocation,Source,TopicTypeId,TopicId,MeasureId,SubMeasureID,SubMeasureIdDisplayOrder
0,AL,Alabama,2004,OW,The Tax Burden on Tobacco,Cigarette Sales,Average Cost per pack,"3,569",$,Dollars,"(32.840571122, -86.631860762)","Table 13- Orzechowski and Walker, Tax Burden o...",POL,450POL,450CGS,455CGS,1
1,AL,Alabama,2004,OW,The Tax Burden on Tobacco,Cigarette Sales,Cigarette Consumption (Pack Sales Per Capita),"87,9",NaN,Pack,"(32.840571122, -86.631860762)","Table 11- Orzechowski and Walker, Tax Burden o...",POL,450POL,450CGS,453CGS,2
2,AK,Alaska,2004,OW,The Tax Burden on Tobacco,Cigarette Sales,Average Cost per pack,"5,03",$,Dollars,"(64.845079957001, -147.722059036)","Table 13- Orzechowski and Walker, Tax Burden o...",POL,450POL,450CGS,455CGS,1
3,AK,Alaska,2004,OW,The Tax Burden on Tobacco,Cigarette Sales,Cigarette Consumption (Pack Sales Per Capita),"63,6",NaN,Pack,"(64.845079957001, -147.722059036)","Table 11- Orzechowski and Walker, Tax Burden o...",POL,450POL,450CGS,453CGS,2
4,AZ,Arizona,2004,OW,The Tax Burden on Tobacco,Cigarette Sales,Cigarette Consumption (Pack Sales Per Capita),"42,5",NaN,Pack,"(34.86597028, -111.763811277)","Table 11- Orzechowski and Walker, Tax Burden o...",POL,450POL,450CGS,453CGS,2

Информация о столбцах:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3570 entries, 0 to 3569
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   LocationAbbr              3570 non-null   object
 1   LocationDesc              3570 non-null   object
 2   Year                      3570 non-null   int64
 3   Datasource                3570 non-null   object
 4   TopicDesc                 3570 non-null   object
 5   MeasureDesc               3570 non-null   object
 6   SubMeasureDesc            3570 non-null   object
 7   Data_Value                3570 non-null   object
 8   Data_Value_Unit           1785 non-null   object
 9   Data_Value_Type           3570 non-null   object
 10  GeoLocation               3570 non-null   object
 11  Source                    3570 non-null   object
 12  TopicTypeId               3570 non-null   object
 13  TopicId                   3570 non-null   object
 14  MeasureId                 3570 non-null   object
 15  SubMeasureID              3570 non-null   object
 16  SubMeasureIdDisplayOrder  3570 non-null   int64
dtypes: int64(2), object(15)
memory usage: 474.3+ KB

--- Загрузка файла: niaaa_apparent_per_capita_consumption_1977_2023.csv ---
Файл успешно загружен!
Первые 5 строк:

,state,state_name,year,ethanol_beer_gallons_per_capita,ethanol_wine_gallons_per_capita,ethanol_spirit_gallons_per_capita,ethanol_all_drinks_gallons_per_capita,number_of_beers,number_of_glasses_wine,number_of_shots_liquor,number_of_drinks_total
0,alabama,Alabama,1977,0.97,0.12,0.82,1.92,229.9259,23.8140,170.2514,409.6000
1,alabama,Alabama,1978,0.95,0.12,0.85,1.92,225.1852,23.8140,176.4801,409.6000
2,alabama,Alabama,1979,0.96,0.12,0.82,1.90,227.5556,23.8140,170.2514,405.3333
3,alabama,Alabama,1980,0.95,0.16,0.74,1.86,225.1852,31.7519,153.6415,396.8000
4,alabama,Alabama,1981,1.00,0.19,0.73,1.91,237.0370,37.7054,151.5653,407.4667

Информация о столбцах:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2632 entries, 0 to 2631
Data columns (total 11 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   state                                  2632 non-null   object
 1   state_name                             2632 non-null   object
 2   year                                   2632 non-null   int64
 3   ethanol_beer_gallons_per_capita        2632 non-null   float64
 4   ethanol_wine_gallons_per_capita        2632 non-null   float64
 5   ethanol_spirit_gallons_per_capita      2632 non-null   float64
 6   ethanol_all_drinks_gallons_per_capita  2632 non-null   float64
 7   number_of_beers                        2632 non-null   float64
 8   number_of_glasses_wine                 2632 non-null   float64
 9   number_of_shots_liquor                 2632 non-null   float64
 10  number_of_drinks_total                 2632 non-null   float64
dtypes: float64(8), int64(1), object(2)
memory usage: 226.3+ KB

--- Загрузка файла: USStatisticAges1.csv ---
Файл успешно загружен!
Первые 5 строк:

,Label (Grouping),Alabama!!Total population!!Number,Alabama!!Total population!!Percent,Alaska!!Total population!!Number,Alaska!!Total population!!Percent,Arizona!!Total population!!Number,Arizona!!Total population!!Percent,Arkansas!!Total population!!Number,Arkansas!!Total population!!Percent,California!!Total population!!Number,...,Washington!!Total population!!Number,Washington!!Total population!!Percent,West Virginia!!Total population!!Number,West Virginia!!Total population!!Percent,Wisconsin!!Total population!!Number,Wisconsin!!Total population!!Percent,Wyoming!!Total population!!Number,Wyoming!!Total population!!Percent,Puerto Rico!!Total population!!Number,Puerto Rico!!Total population!!Percent
0,15 to 19 years,"324,58",7.3,"50,094",8.0,"367,722",7.2,"198,765",7.4,"2,450,888",...,"427,968",7.3,"125,578",6.9,"407,195",7.6,"41,903",8.5,"313,436",8.2
1,20 to 24 years,"306,865",6.9,"39,892",6.4,"362,86",7.1,"181,598",6.8,"2,381,288",...,"390,185",6.6,"120,109",6.6,"357,292",6.7,"33,455",6.8,"301,191",7.9

Информация о столбцах:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Columns: 105 entries, Label (Grouping) to Puerto Rico!!Total population!!Percent
dtypes: float64(52), object(53)
memory usage: 1.8+ KB

--- Загрузка файла: GdpPerCapita1.csv ---
Файл успешно загружен!
Первые 5 строк:

,Unnamed: 0,GeoName,1970,1971,1972,1973,1974,1975,1976,1977,...,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004
0,1000,Alabama,2781.0,3032.0,3303.0,3677.0,4019.0,4460.0,4896.0,5324.0,...,17754.0,18333.0,19057.0,20103.0,20648.0,21527.0,22243.0,23193.0,24330.0,25962.0
1,5000,Arkansas,2623.0,2893.0,3178.0,3676.0,3993.0,4355.0,4726.0,5183.0,...,16653.0,17394.0,17981.0,18836.0,19433.0,20168.0,21202.0,21949.0,23360.0,24746.0
2,6000,California,4430.0,4701.0,5013.0,5477.0,5998.0,6602.0,7121.0,7699.0,...,21682.0,22544.0,23262.0,24763.0,25769.0,27424.0,28677.0,29843.0,31148.0,32732.0
3,8000,Colorado,3800.0,4160.0,4452.0,4923.0,5396.0,5939.0,6385.0,6904.0,...,21883.0,22858.0,23760.0,25540.0,26610.0,28739.0,29944.0,30322.0,31014.0,31909.0
4,9000,Connecticut,4485.0,4764.0,5050.0,5537.0,6024.0,6547.0,6974.0,7678.0,...,27096.0,27794.0,28981.0,30870.0,32285.0,34766.0,36660.0,37949.0,38568.0,40352.0

Информация о столбцах:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 37 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  50 non-null     object
 1   GeoName     46 non-null     object
 2   1970        46 non-null     float64
 3   1971        46 non-null     float64
 4   1972        46 non-null     float64
 5   1973        46 non-null     float64
 6   1974        46 non-null     float64
 7   1975        46 non-null     float64
 8   1976        46 non-null     float64
 9   1977        46 non-null     float64
 10  1978        46 non-null     float64
 11  1979        46 non-null     float64
 12  1980        46 non-null     float64
 13  1981        46 non-null     float64
 14  1982        46 non-null     float64
 15  1983        46 non-null     float64
 16  1984        46 non-null     float64
 17  1985        46 non-null     float64
 18  1986        46 non-null     float64
 19  1987        46 non-null     float64
 20  1988        46 non-null     float64
 21  1989        46 non-null     float64
 22  1990        46 non-null     float64
 23  1991        46 non-null     float64
 24  1992        46 non-null     float64
 25  1993        46 non-null     float64
 26  1994        46 non-null     float64
 27  1995        46 non-null     float64
 28  1996        46 non-null     float64
 29  1997        46 non-null     float64
 30  1998        46 non-null     float64
 31  1999        46 non-null     float64
 32  2000        46 non-null     float64
 33  2001        46 non-null     float64
 34  2002        46 non-null     float64
 35  2003        46 non-null     float64
 36  2004        46 non-null     float64
dtypes: float64(35), object(2)
memory usage: 14.9+ KB

--- Загрузка файла: final_merged_data.csv ---
Файл успешно загружен!
Первые 5 строк:

,State,Beer_Consumption_Per_Capita,GDP_Per_Capita,Cigarette_Packs_Per_Capita_1975,Cigarette_Packs_Per_Capita_1980,Cigarette_Packs_Per_Capita_1988,Average_Cigarette_Price,Percentage_15_24
0,Alabama,1.086,9664.666667,111.7,123.2,112.1,96.200000,14.2
1,Arkansas,1.066,9313.222222,114.8,131.8,121.5,97.233333,14.2
2,California,1.342,13826.888889,127.1,120.2,90.1,96.566667,14.2
3,Colorado,1.474,12905.555556,131.0,131.0,94.6,91.088889,14.2
4,Connecticut,1.118,15211.888889,110.2,118.0,104.8,111.811111,11.9

Информация о столбцах:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   State                            39 non-null     object
 1   Beer_Consumption_Per_Capita      39 non-null     float64
 2   GDP_Per_Capita                   39 non-null     float64
 3   Cigarette_Packs_Per_Capita_1975  39 non-null     float64
 4   Cigarette_Packs_Per_Capita_1980  39 non-null     float64
 5   Cigarette_Packs_Per_Capita_1988  39 non-null     float64
 6   Average_Cigarette_Price          39 non-null     float64
 7   Percentage_15_24                 39 non-null     float64
dtypes: float64(7), object(1)
memory usage: 2.6+ KB

# Task
The primary goal is to integrate data from several CSV files related to alcohol consumption, GDP per capita, tobacco burden, and age demographics into a single, comprehensive DataFrame. This involves loading each dataset, selecting relevant columns, renaming them for consistency, reshaping data where necessary (e.g., melting wide-format GDP data), and cleaning data types (e.g., converting percentages and monetary values to numeric). Finally, all processed DataFrames will be merged based on 'State' and 'Year' (where applicable) to create a unified dataset. The task concludes with a review of the final merged DataFrame's structure and content.

## Prepare Alcohol Consumption Data

### Subtask:
Load the alcohol consumption dataset, select relevant columns, rename them for consistency, and ensure 'Year' is an integer.

**Reasoning**:
The first step is to load the specified CSV file for alcohol consumption, select the necessary columns, and rename them as instructed.

In [ ]:
df_alcohol_consumption_temp = dfs['niaaa_apparent_per_capita_consumption_1977_2023.csv']
df_alcohol_consumption = df_alcohol_consumption_temp[['state_name', 'year', 'ethanol_beer_gallons_per_capita']].copy()
df_alcohol_consumption.rename(columns={'state_name': 'State', 'year': 'Year', 'ethanol_beer_gallons_per_capita': 'Beer_Consumption_Per_Capita'}, inplace=True)
df_alcohol_consumption['Year'] = df_alcohol_consumption['Year'].astype(int)

print("Processed Alcohol Consumption Data:")
display(df_alcohol_consumption.head())
print("\nInfo of Alcohol Consumption Data:")
df_alcohol_consumption.info()

Processed Alcohol Consumption Data:

     State  Year  Beer_Consumption_Per_Capita
0  Alabama  1977                         0.97
1  Alabama  1978                         0.95
2  Alabama  1979                         0.96
3  Alabama  1980                         0.95
4  Alabama  1981                         1.00

Info of Alcohol Consumption Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2632 entries, 0 to 2631
Data columns (total 3 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   State                        2632 non-null   object
 1   Year                         2632 non-null   int64
 2   Beer_Consumption_Per_Capita  2632 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 61.8+ KB

# Task
The primary goal is to integrate data from several CSV files related to alcohol consumption, GDP per capita, tobacco burden, and age demographics into a single, comprehensive DataFrame. This involves loading each dataset, selecting relevant columns, renaming them for consistency, reshaping data where necessary (e.g., melting wide-format GDP data), and cleaning data types (e.g., converting percentages and monetary values to numeric). Finally, all processed DataFrames will be merged based on 'State' and 'Year' (where applicable) to create a unified dataset. The task concludes with a review of the final merged DataFrame's structure and content.

## Filter Beer Consumption Data

### Subtask:
Filter the `df_alcohol_consumption` DataFrame to include only data for years up to and including 2004, and then display the head and information of the resulting DataFrame.

**Reasoning**:
Filter the DataFrame to include data up to 2004, and then display its head and info to verify the operation.

In [ ]:
df_beer_consumption_2004 = df_alcohol_consumption[df_alcohol_consumption['Year'] <= 2004].copy()

print("Filtered Alcohol Consumption Data (up to 2004):")
display(df_beer_consumption_2004.head())

print("\nInfo of Filtered Alcohol Consumption Data:")
df_beer_consumption_2004.info()

Filtered Alcohol Consumption Data (up to 2004):

     State  Year  Beer_Consumption_Per_Capita
0  Alabama  1977                         0.97
1  Alabama  1978                         0.95
2  Alabama  1979                         0.96
3  Alabama  1980                         0.95
4  Alabama  1981                         1.00

Info of Filtered Alcohol Consumption Data:
<class 'pandas.core.frame.DataFrame'>
Index: 1568 entries, 0 to 2612
Data columns (total 3 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   State                        1568 non-null   object
 1   Year                         1568 non-null   int64
 2   Beer_Consumption_Per_Capita  1568 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 49.0+ KB

## Display Filtered Data Info

### Subtask:
Display the head and information of the new `df_beer_consumption_2004` DataFrame to confirm the filtering.

# Task
The primary goal is to integrate data from several CSV files related to alcohol consumption, GDP per capita, tobacco burden, and age demographics into a single, comprehensive DataFrame. This involves loading each dataset, selecting relevant columns, renaming them for consistency, reshaping data where necessary (e.g., melting wide-format GDP data), and cleaning data types (e.g., converting percentages and monetary values to numeric). Finally, all processed DataFrames will be merged based on 'State' and 'Year' (where applicable) to create a unified dataset. The task concludes with a review of the final merged DataFrame's structure and content.

## Filter Data for Years 1984-1988

### Subtask:
Filter the `df_beer_consumption_2004` DataFrame to include only the years from 1984 to 1988 (inclusive).

**Reasoning**:
Filter the `df_beer_consumption_2004` DataFrame to include only data for years between 1984 and 1988, then display the head and information of the resulting DataFrame.

In [ ]:
df_beer_consumption_1984_1988 = df_alcohol_consumption[
    (df_alcohol_consumption['Year'] >= 1984) &
    (df_alcohol_consumption['Year'] <= 1988)
].copy()

print("Filtered Alcohol Consumption Data (1984-1988):")
display(df_beer_consumption_1984_1988.head())

print("\nInfo of Filtered Alcohol Consumption Data (1984-1988):")
df_beer_consumption_1984_1988.info()

df_average_beer_consumption = df_beer_consumption_1984_1988.groupby('State')['Beer_Consumption_Per_Capita'].mean().reset_index()

Filtered Alcohol Consumption Data (1984-1988):

      State  Year  Beer_Consumption_Per_Capita
7   Alabama  1984                         1.03
8   Alabama  1985                         1.07
9   Alabama  1986                         1.10
10  Alabama  1987                         1.11
11  Alabama  1988                         1.12

Info of Filtered Alcohol Consumption Data (1984-1988):
<class 'pandas.core.frame.DataFrame'>
Index: 280 entries, 7 to 2596
Data columns (total 3 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   State                        280 non-null    object
 1   Year                         280 non-null    int64
 2   Beer_Consumption_Per_Capita  280 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 8.8+ KB

## Calculate Average Beer Consumption per State

### Subtask:
Group the filtered data by 'State' and calculate the mean of 'Beer_Consumption_Per_Capita' for each state.

**Reasoning**:
Group the DataFrame by 'State' and calculate the mean of 'Beer_Consumption_Per_Capita' to get the average consumption per state.

In [ ]:
df_average_beer_consumption = df_beer_consumption_1984_1988.groupby('State')['Beer_Consumption_Per_Capita'].mean().reset_index()

print("Average Beer Consumption Per State (1984-1988):")
display(df_average_beer_consumption.head())

Average Beer Consumption Per State (1984-1988):

        State  Beer_Consumption_Per_Capita
0     Alabama                        1.086
1      Alaska                        1.618
2     Arizona                        1.638
3    Arkansas                        1.066
4  California                        1.342

**Reasoning**:
Display the information of the `df_average_beer_consumption` DataFrame to confirm its structure and data types, completing the verification of the calculated averages.

In [ ]:
print("\nInfo of Average Beer Consumption Per State (1984-1988):")
df_average_beer_consumption.info()

Info of Average Beer Consumption Per State (1984-1988):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 2 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   State                        56 non-null     object
 1   Beer_Consumption_Per_Capita  56 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.0+ KB

## Display Average Consumption

### Subtask:
Display the head and information of the DataFrame containing the average beer consumption per state.

**Reasoning**:
Displaying the head of the DataFrame is the remaining instruction for this subtask. The info was already displayed in the previous cell output.

In [ ]:
print("Head of Average Beer Consumption Per State (1984-1988):")
display(df_average_beer_consumption.head())

Head of Average Beer Consumption Per State (1984-1988):

        State  Beer_Consumption_Per_Capita
0     Alabama                        1.086
1      Alaska                        1.618
2     Arizona                        1.638
3    Arkansas                        1.066
4  California                        1.342

# Task
The primary goal is to integrate data from several CSV files related to alcohol consumption, GDP per capita, tobacco burden, and age demographics into a single, comprehensive DataFrame. This involves loading each dataset, selecting relevant columns, renaming them for consistency, reshaping data where necessary (e.g., melting wide-format GDP data), and cleaning data types (e.g., converting percentages and monetary values to numeric). Finally, all processed DataFrames will be merged based on 'State' and 'Year' (where applicable) to create a unified dataset. The task concludes with a review of the final merged DataFrame's structure and content.

## Load and Inspect GDP Data

### Subtask:
Load the GDP per capita dataset from `dfs['GdpPerCapita1.csv']` and display its head and info to understand its structure.

**Reasoning**:
Access the GDP dataframe from the `dfs` dictionary, then display its head and info as per the instructions.

In [ ]:
df_gdp_raw = dfs['GdpPerCapita1.csv']
print("Head of GDP Per Capita Data:")
display(df_gdp_raw.head())

print("\nInfo of GDP Per Capita Data:")
df_gdp_raw.info()

Head of GDP Per Capita Data:

,Unnamed: 0,GeoName,1970,1971,1972,1973,1974,1975,1976,1977,...,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004
0,1000,Alabama,2781.0,3032.0,3303.0,3677.0,4019.0,4460.0,4896.0,5324.0,...,17754.0,18333.0,19057.0,20103.0,20648.0,21527.0,22243.0,23193.0,24330.0,25962.0
1,5000,Arkansas,2623.0,2893.0,3178.0,3676.0,3993.0,4355.0,4726.0,5183.0,...,16653.0,17394.0,17981.0,18836.0,19433.0,20168.0,21202.0,21949.0,23360.0,24746.0
2,6000,California,4430.0,4701.0,5013.0,5477.0,5998.0,6602.0,7121.0,7699.0,...,21682.0,22544.0,23262.0,24763.0,25769.0,27424.0,28677.0,29843.0,31148.0,32732.0
3,8000,Colorado,3800.0,4160.0,4452.0,4923.0,5396.0,5939.0,6385.0,6904.0,...,21883.0,22858.0,23760.0,25540.0,26610.0,28739.0,29944.0,30322.0,31014.0,31909.0
4,9000,Connecticut,4485.0,4764.0,5050.0,5537.0,6024.0,6547.0,6974.0,7678.0,...,27096.0,27794.0,28981.0,30870.0,32285.0,34766.0,36660.0,37949.0,38568.0,40352.0

Info of GDP Per Capita Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 37 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  50 non-null     object
 1   GeoName     46 non-null     object
 2   1970        46 non-null     float64
 3   1971        46 non-null     float64
 4   1972        46 non-null     float64
 5   1973        46 non-null     float64
 6   1974        46 non-null     float64
 7   1975        46 non-null     float64
 8   1976        46 non-null     float64
 9   1977        46 non-null     float64
 10  1978        46 non-null     float64
 11  1979        46 non-null     float64
 12  1980        46 non-null     float64
 13  1981        46 non-null     float64
 14  1982        46 non-null     float64
 15  1983        46 non-null     float64
 16  1984        46 non-null     float64
 17  1985        46 non-null     float64
 18  1986        46 non-null     float64
 19  1987        46 non-null     float64
 20  1988        46 non-null     float64
 21  1989        46 non-null     float64
 22  1990        46 non-null     float64
 23  1991        46 non-null     float64
 24  1992        46 non-null     float64
 25  1993        46 non-null     float64
 26  1994        46 non-null     float64
 27  1995        46 non-null     float64
 28  1996        46 non-null     float64
 29  1997        46 non-null     float64
 30  1998        46 non-null     float64
 31  1999        46 non-null     float64
 32  2000        46 non-null     float64
 33  2001        46 non-null     float64
 34  2002        46 non-null     float64
 35  2003        46 non-null     float64
 36  2004        46 non-null     float64
dtypes: float64(35), object(2)
memory usage: 14.9+ KB

## Melt and Clean GDP Data

### Subtask:
Melt the wide-format GDP data into a long format, converting year columns into a 'Year' column and corresponding values into a 'GDP_Per_Capita' column. Ensure 'Year' is an integer and 'GDP_Per_Capita' is numeric. Rename the state column to 'State'.

**Reasoning**:
Identify the year columns, perform the melt operation, convert data types, and rename the 'GeoName' column to 'State' in a single step.

In [ ]:
year_cols = [str(year) for year in range(1970, 2005)]
df_gdp_melted = df_gdp_raw.melt(id_vars=['GeoName'], value_vars=year_cols, var_name='Year', value_name='GDP_Per_Capita')

# Convert 'Year' to integer and 'GDP_Per_Capita' to numeric, coercing errors
df_gdp_melted['Year'] = pd.to_numeric(df_gdp_melted['Year'], errors='coerce').astype(int)
df_gdp_melted['GDP_Per_Capita'] = pd.to_numeric(df_gdp_melted['GDP_Per_Capita'], errors='coerce')

# Rename 'GeoName' to 'State'
df_gdp_cleaned = df_gdp_melted.rename(columns={'GeoName': 'State'})

print("Head of Cleaned and Melted GDP Data:")
display(df_gdp_cleaned.head())

print("\nInfo of Cleaned and Melted GDP Data:")
df_gdp_cleaned.info()

Head of Cleaned and Melted GDP Data:

         State  Year  GDP_Per_Capita
0      Alabama  1970          2781.0
1     Arkansas  1970          2623.0
2   California  1970          4430.0
3     Colorado  1970          3800.0
4  Connecticut  1970          4485.0

Info of Cleaned and Melted GDP Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1785 entries, 0 to 1784
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           1610 non-null   object
 1   Year            1785 non-null   int64
 2   GDP_Per_Capita  1610 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 42.0+ KB

## Filter GDP Data (1980-1988)

### Subtask:
Filter the processed GDP DataFrame (`df_gdp_cleaned`) to include only data for the years 1980 to 1988 (inclusive).

**Reasoning**:
I need to filter the `df_gdp_cleaned` DataFrame for the specified year range (1980-1988) and then display the head and info of the resulting DataFrame.

In [ ]:
df_gdp_1980_1988 = df_gdp_cleaned[
    (df_gdp_cleaned['Year'] >= 1980) &
    (df_gdp_cleaned['Year'] <= 1988)
].copy()

print("Head of Filtered GDP Data (1980-1988):")
display(df_gdp_1980_1988.head())

print("\nInfo of Filtered GDP Data (1980-1988):")
df_gdp_1980_1988.info()

Head of Filtered GDP Data (1980-1988):

           State  Year  GDP_Per_Capita
510      Alabama  1980          7084.0
511     Arkansas  1980          6776.0
512   California  1980         10439.0
513     Colorado  1980          9590.0
514  Connecticut  1980         10598.0

Info of Filtered GDP Data (1980-1988):
<class 'pandas.core.frame.DataFrame'>
Index: 459 entries, 510 to 968
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           414 non-null    object
 1   Year            459 non-null    int64
 2   GDP_Per_Capita  414 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 14.3+ KB

## Calculate Average GDP per State

### Subtask:
Group the filtered GDP data by 'State' and calculate the mean of 'GDP_Per_Capita' for each state, creating a new DataFrame with average GDP for the specified period.

**Reasoning**:
I need to group the `df_gdp_1980_1988` DataFrame by 'State' and calculate the mean of 'GDP_Per_Capita' as per the instructions.

In [ ]:
df_average_gdp = df_gdp_1980_1988.groupby('State')['GDP_Per_Capita'].mean().reset_index()

print("Average GDP Per Capita Per State (1980-1988):")
display(df_average_gdp.head())

Average GDP Per Capita Per State (1980-1988):

         State  GDP_Per_Capita
0      Alabama     9664.666667
1     Arkansas     9313.222222
2   California    13826.888889
3     Colorado    12905.555556
4  Connecticut    15211.888889

**Reasoning**:
Display the info of the `df_average_gdp` DataFrame to confirm its structure and data types, completing the verification of the calculated averages.

In [ ]:
print("\nInfo of Average GDP Per Capita Per State (1980-1988):")
df_average_gdp.info()

Info of Average GDP Per Capita Per State (1980-1988):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           46 non-null     object
 1   GDP_Per_Capita  46 non-null     float64
dtypes: float64(1), object(1)
memory usage: 868.0+ bytes

**Reasoning**:
Display the head of the `df_average_gdp` DataFrame as per the instructions to visually confirm the results of the average GDP calculation.

In [ ]:
print("Head of Average GDP Per Capita Per State (1980-1988):")
display(df_average_gdp.head())

Head of Average GDP Per Capita Per State (1980-1988):

         State  GDP_Per_Capita
0      Alabama     9664.666667
1     Arkansas     9313.222222
2   California    13826.888889
3     Colorado    12905.555556
4  Connecticut    15211.888889

## Display Average GDP

### Subtask:
Confirm that the head and information of the DataFrame containing the average GDP per capita for each state (1980-1988) have been displayed.

## Final Task

### Subtask:
Summarize the completion of the GDP data preparation and the calculation of average GDP per state for 1980-1988, noting its readiness for integration.

# Task
The primary goal is to integrate data from several CSV files related to alcohol consumption, GDP per capita, tobacco burden, and age demographics into a single, comprehensive DataFrame. This involves loading each dataset, selecting relevant columns, renaming them for consistency, reshaping data where necessary (e.g., melting wide-format GDP data), and cleaning data types (e.g., converting percentages and monetary values to numeric). Finally, all processed DataFrames will be merged based on 'State' and 'Year' (where applicable) to create a unified dataset. The task concludes with a review of the final merged DataFrame's structure and content.

## Load and Inspect Tobacco Data

### Subtask:
Загрузите и первично проанализируйте DataFrame с данными о табаке из `dfs['The_Tax_Burden_on_Tobacco,_1970-2019_20260811.csv']`. Проверьте столбцы `TopicDesc`, `MeasureDesc`, `LocationDesc`, `Year` и `Data_Value`, чтобы понять их структуру.

**Reasoning**:
Access the 'The_Tax_Burden_on_Tobacco,_1970-2019_20260811.csv' DataFrame from the `dfs` dictionary, display its head, and then its info as per the instructions.

In [3]:
df_tobacco_raw = dfs['The_Tax_Burden_on_Tobacco,_1970-2019_20260811.csv']
print("Head of Tobacco Data:")
display(df_tobacco_raw.head())

print("\nInfo of Tobacco Data:")
df_tobacco_raw.info()

Head of Tobacco Data:

,LocationAbbr,LocationDesc,Year,Datasource,TopicDesc,MeasureDesc,SubMeasureDesc,Data_Value,Data_Value_Unit,Data_Value_Type,GeoLocation,Source,TopicTypeId,TopicId,MeasureId,SubMeasureID,SubMeasureIdDisplayOrder
0,AL,Alabama,2004,OW,The Tax Burden on Tobacco,Cigarette Sales,Average Cost per pack,"3,569",$,Dollars,"(32.840571122, -86.631860762)","Table 13- Orzechowski and Walker, Tax Burden o...",POL,450POL,450CGS,455CGS,1
1,AL,Alabama,2004,OW,The Tax Burden on Tobacco,Cigarette Sales,Cigarette Consumption (Pack Sales Per Capita),"87,9",NaN,Pack,"(32.840571122, -86.631860762)","Table 11- Orzechowski and Walker, Tax Burden o...",POL,450POL,450CGS,453CGS,2
2,AK,Alaska,2004,OW,The Tax Burden on Tobacco,Cigarette Sales,Average Cost per pack,"5,03",$,Dollars,"(64.845079957001, -147.722059036)","Table 13- Orzechowski and Walker, Tax Burden o...",POL,450POL,450CGS,455CGS,1
3,AK,Alaska,2004,OW,The Tax Burden on Tobacco,Cigarette Sales,Cigarette Consumption (Pack Sales Per Capita),"63,6",NaN,Pack,"(64.845079957001, -147.722059036)","Table 11- Orzechowski and Walker, Tax Burden o...",POL,450POL,450CGS,453CGS,2
4,AZ,Arizona,2004,OW,The Tax Burden on Tobacco,Cigarette Sales,Cigarette Consumption (Pack Sales Per Capita),"42,5",NaN,Pack,"(34.86597028, -111.763811277)","Table 11- Orzechowski and Walker, Tax Burden o...",POL,450POL,450CGS,453CGS,2

Info of Tobacco Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3570 entries, 0 to 3569
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   LocationAbbr              3570 non-null   object
 1   LocationDesc              3570 non-null   object
 2   Year                      3570 non-null   int64
 3   Datasource                3570 non-null   object
 4   TopicDesc                 3570 non-null   object
 5   MeasureDesc               3570 non-null   object
 6   SubMeasureDesc            3570 non-null   object
 7   Data_Value                3570 non-null   object
 8   Data_Value_Unit           1785 non-null   object
 9   Data_Value_Type           3570 non-null   object
 10  GeoLocation               3570 non-null   object
 11  Source                    3570 non-null   object
 12  TopicTypeId               3570 non-null   object
 13  TopicId                   3570 non-null   object
 14  MeasureId                 3570 non-null   object
 15  SubMeasureID              3570 non-null   object
 16  SubMeasureIdDisplayOrder  3570 non-null   int64
dtypes: int64(2), object(15)
memory usage: 474.3+ KB

## Process Tobacco Consumption Data

### Subtask:
Отфильтруйте DataFrame о табаке, чтобы выделить данные о 'Cigarette Use - Sales (packs per capita)'. Выберите и переименуйте столбцы: `LocationDesc` в `State`, `Year` в `Year` и `Data_Value` в `Cigarette_Packs_Per_Capita`. Преобразуйте `Cigarette_Packs_Per_Capita` в числовой тип, обработав запятые и возможные нечисловые значения. Отфильтруйте полученный DataFrame для лет 1975, 1980 и 1988. Рассчитайте среднее значение `Cigarette_Packs_Per_Capita` для каждого `State` за эти годы, сохранив результат в DataFrame `df_average_tobacco_consumption`.

**Reasoning**:
Filter the `df_tobacco_raw` DataFrame for rows where `SubMeasureDesc` is 'Cigarette Consumption (Pack Sales Per Capita)', select the specified columns, rename them, and clean the `Cigarette_Packs_Per_Capita` column by removing commas and converting it to a numeric type.

In [ ]:
df_tobacco_consumption = df_tobacco_raw[
    df_tobacco_raw['SubMeasureDesc'] == 'Cigarette Consumption (Pack Sales Per Capita)'
].copy()

df_tobacco_consumption = df_tobacco_consumption[[
    'LocationDesc', 'Year', 'Data_Value'
]]

df_tobacco_consumption.rename(columns={
    'LocationDesc': 'State',
    'Year': 'Year',
    'Data_Value': 'Cigarette_Packs_Per_Capita'
}, inplace=True)

# Clean 'Cigarette_Packs_Per_Capita' column: remove commas and convert to numeric
df_tobacco_consumption['Cigarette_Packs_Per_Capita'] = df_tobacco_consumption['Cigarette_Packs_Per_Capita'].str.replace(',', '.', regex=False)
df_tobacco_consumption['Cigarette_Packs_Per_Capita'] = pd.to_numeric(df_tobacco_consumption['Cigarette_Packs_Per_Capita'], errors='coerce')

print("Processed Tobacco Consumption Data (Cigarette Packs Per Capita):")
display(df_tobacco_consumption.head())
print("\nInfo of Processed Tobacco Consumption Data:")
df_tobacco_consumption.info()

Processed Tobacco Consumption Data (Cigarette Packs Per Capita):

        State  Year  Cigarette_Packs_Per_Capita
1     Alabama  2004                        87.9
3      Alaska  2004                        63.6
4     Arizona  2004                        42.5
7    Arkansas  2004                        79.8
9  California  2004                        33.1

Info of Processed Tobacco Consumption Data:
<class 'pandas.core.frame.DataFrame'>
Index: 1785 entries, 1 to 3569
Data columns (total 3 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   State                       1785 non-null   object
 1   Year                        1785 non-null   int64
 2   Cigarette_Packs_Per_Capita  1785 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 55.8+ KB

**Reasoning**:
Filter the `df_tobacco_consumption` DataFrame for the specified years (1975, 1980, 1988), then group by 'State' and calculate the mean of 'Cigarette_Packs_Per_Capita'. Display the head and info of the new DataFrame `df_average_tobacco_consumption`.

In [ ]:
df_tobacco_consumption_filtered_years = df_tobacco_consumption[
    df_tobacco_consumption['Year'].isin([1975, 1980, 1988])
].copy()

# df_average_tobacco_consumption = df_tobacco_consumption_filtered.groupby('State')['Cigarette_Packs_Per_Capita'].mean().reset_index()

print("Tobacco Consumption Per State (1975, 1980, 1988):")
display(df_tobacco_consumption_filtered_years.head())

print("\nInfo of Tobacco Consumption Per State (1975, 1980, 1988):")
df_tobacco_consumption_filtered_years.info()

Tobacco Consumption Per State (1975, 1980, 1988):

           State  Year  Cigarette_Packs_Per_Capita
1633     Alabama  1988                       112.1
1634      Alaska  1988                        80.0
1637     Arizona  1988                       102.2
1639    Arkansas  1988                       121.5
1640  California  1988                        90.1

Info of Tobacco Consumption Per State (1975, 1980, 1988):
<class 'pandas.core.frame.DataFrame'>
Index: 153 entries, 1633 to 3059
Data columns (total 3 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   State                       153 non-null    object
 1   Year                        153 non-null    int64
 2   Cigarette_Packs_Per_Capita  153 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 4.8+ KB

## Process Cigarette Price Data

### Subtask:
Отфильтруйте DataFrame о табаке, чтобы выделить данные о 'Cigarette Prices - Average price per pack'. Выберите и переименуйте столбцы: `LocationDesc` в `State`, `Year` в `Year` и `Data_Value` в `Average_Cigarette_Price`. Преобразуйте `Average_Cigarette_Price` в числовой тип, обработав запятые и возможные нечисловые значения. Отфильтруйте полученный DataFrame для лет с 1980 по 1988 (включительно). Рассчитайте среднее значение `Average_Cigarette_Price` для каждого `State` за эти годы, сохранив результат в DataFrame `df_average_cigarette_price`.

**Reasoning**:
The instructions require filtering the raw tobacco data, selecting and renaming columns, cleaning the price column, filtering by year, and then calculating the average price per state. All these steps are related to preparing the `df_average_cigarette_price` DataFrame.

In [ ]:
df_cigarette_prices_temp = df_tobacco_raw[
    df_tobacco_raw['SubMeasureDesc'] == 'Average Cost per pack'
].copy()

df_cigarette_prices = df_cigarette_prices_temp[[
    'LocationDesc', 'Year', 'Data_Value'
]].copy()

df_cigarette_prices.rename(columns={
    'LocationDesc': 'State',
    'Year': 'Year',
    'Data_Value': 'Average_Cigarette_Price'
}, inplace=True)

# Clean 'Average_Cigarette_Price' column: remove commas and convert to numeric
df_cigarette_prices['Average_Cigarette_Price'] = df_cigarette_prices['Average_Cigarette_Price'].str.replace(',', '.', regex=False)
df_cigarette_prices['Average_Cigarette_Price'] = pd.to_numeric(df_cigarette_prices['Average_Cigarette_Price'], errors='coerce')

# Filter for years 1980 to 1988
df_cigarette_prices_filtered = df_cigarette_prices[
    (df_cigarette_prices['Year'] >= 1980) &
    (df_cigarette_prices['Year'] <= 1988)
].copy()

# Calculate the mean 'Average_Cigarette_Price' for each State
df_average_cigarette_price = df_cigarette_prices_filtered.groupby('State')['Average_Cigarette_Price'].mean().reset_index()

# Convert to cents
df_average_cigarette_price['Average_Cigarette_Price'] = df_average_cigarette_price['Average_Cigarette_Price'] * 100

print("Average Cigarette Price Per State (1980-1988):")
display(df_average_cigarette_price.head())

print("\nInfo of Average Cigarette Price Per State (1980-1988):")
df_average_cigarette_price.info()

Average Cigarette Price Per State (1980-1988):

        State  Average_Cigarette_Price
0     Alabama                96.200000
1      Alaska               101.944444
2     Arizona                96.444444
3    Arkansas                97.233333
4  California                96.566667

Info of Average Cigarette Price Per State (1980-1988):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State                    51 non-null     object
 1   Average_Cigarette_Price  51 non-null     float64
dtypes: float64(1), object(1)
memory usage: 948.0+ bytes

## Prepare Age Demographics Data

### Subtask:
Загрузите и первично проанализируйте DataFrame с данными о возрастных группах из `dfs['USStatisticAges1.csv']`. Проверьте структуру данных, чтобы определить столбцы, относящиеся к штату, году и проценту населения в возрасте 15-24 лет.

**Reasoning**:
Access the 'USStatisticAges1.csv' DataFrame from the `dfs` dictionary, display its head, and then its info to understand its structure.

In [ ]:
df_age_raw = dfs['USStatisticAges1.csv']
print("Head of Age Demographics Data:")
display(df_age_raw.head())

print("\nInfo of Age Demographics Data:")
df_age_raw.info()

Head of Age Demographics Data:

,Label (Grouping),Alabama!!Total population!!Number,Alabama!!Total population!!Percent,Alaska!!Total population!!Number,Alaska!!Total population!!Percent,Arizona!!Total population!!Number,Arizona!!Total population!!Percent,Arkansas!!Total population!!Number,Arkansas!!Total population!!Percent,California!!Total population!!Number,...,Washington!!Total population!!Number,Washington!!Total population!!Percent,West Virginia!!Total population!!Number,West Virginia!!Total population!!Percent,Wisconsin!!Total population!!Number,Wisconsin!!Total population!!Percent,Wyoming!!Total population!!Number,Wyoming!!Total population!!Percent,Puerto Rico!!Total population!!Number,Puerto Rico!!Total population!!Percent
0,15 to 19 years,"324,58",7.3,"50,094",8.0,"367,722",7.2,"198,765",7.4,"2,450,888",...,"427,968",7.3,"125,578",6.9,"407,195",7.6,"41,903",8.5,"313,436",8.2
1,20 to 24 years,"306,865",6.9,"39,892",6.4,"362,86",7.1,"181,598",6.8,"2,381,288",...,"390,185",6.6,"120,109",6.6,"357,292",6.7,"33,455",6.8,"301,191",7.9

Info of Age Demographics Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Columns: 105 entries, Label (Grouping) to Puerto Rico!!Total population!!Percent
dtypes: float64(52), object(53)
memory usage: 1.8+ KB

In [ ]:
import numpy as np

# Filter for columns that contain percentage data (excluding the 'Number' columns)
percentage_cols = [col for col in df_age_raw.columns if '!!Percent' in col]
df_age_percentages = df_age_raw[['Label (Grouping)'] + percentage_cols].copy()

# Clean up column names to just state names
df_age_percentages.columns = ['Label (Grouping)'] + [col.split('!!')[0] for col in percentage_cols]

# Clean up 'Label (Grouping)' values by stripping whitespace
df_age_percentages['Label (Grouping)'] = df_age_percentages['Label (Grouping)'].str.strip()

print("Head of Age Demographics Data (Percentages Only):")
display(df_age_percentages.head())
print("\nInfo of Age Demographics Data (Percentages Only):")
df_age_percentages.info()

Head of Age Demographics Data (Percentages Only):

,Label (Grouping),Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,15 to 19 years,7.3,8.0,7.2,7.4,7.2,7.1,6.4,7.1,6.6,...,6.9,7.8,9.7,7.5,6.8,7.3,6.9,7.6,8.5,8.2
1,20 to 24 years,6.9,6.4,7.1,6.8,7.0,7.1,5.5,6.6,9.1,...,6.8,7.4,10.1,6.2,6.8,6.6,6.6,6.7,6.8,7.9

Info of Age Demographics Data (Percentages Only):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 53 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Label (Grouping)      2 non-null      object
 1   Alabama               2 non-null      float64
 2   Alaska                2 non-null      float64
 3   Arizona               2 non-null      float64
 4   Arkansas              2 non-null      float64
 5   California            2 non-null      float64
 6   Colorado              2 non-null      float64
 7   Connecticut           2 non-null      float64
 8   Delaware              2 non-null      float64
 9   District of Columbia  2 non-null      float64
 10  Florida               2 non-null      float64
 11  Georgia               2 non-null      float64
 12  Hawaii                2 non-null      float64
 13  Idaho                 2 non-null      float64
 14  Illinois              2 non-null      float64
 15  Indiana               2 non-null      float64
 16  Iowa                  2 non-null      float64
 17  Kansas                2 non-null      float64
 18  Kentucky              2 non-null      float64
 19  Louisiana             2 non-null      float64
 20  Maine                 2 non-null      float64
 21  Maryland              2 non-null      float64
 22  Massachusetts         2 non-null      float64
 23  Michigan              2 non-null      float64
 24  Minnesota             2 non-null      float64
 25  Mississippi           2 non-null      float64
 26  Missouri              2 non-null      float64
 27  Montana               2 non-null      float64
 28  Nebraska              2 non-null      float64
 29  Nevada                2 non-null      float64
 30  New Hampshire         2 non-null      float64
 31  New Jersey            2 non-null      float64
 32  New Mexico            2 non-null      float64
 33  New York              2 non-null      float64
 34  North Carolina        2 non-null      float64
 35  North Dakota          2 non-null      float64
 36  Ohio                  2 non-null      float64
 37  Oklahoma              2 non-null      float64
 38  Oregon                2 non-null      float64
 39  Pennsylvania          2 non-null      float64
 40  Rhode Island          2 non-null      float64
 41  South Carolina        2 non-null      float64
 42  South Dakota          2 non-null      float64
 43  Tennessee             2 non-null      float64
 44  Texas                 2 non-null      float64
 45  Utah                  2 non-null      float64
 46  Vermont               2 non-null      float64
 47  Virginia              2 non-null      float64
 48  Washington            2 non-null      float64
 49  West Virginia         2 non-null      float64
 50  Wisconsin             2 non-null      float64
 51  Wyoming               2 non-null      float64
 52  Puerto Rico           2 non-null      float64
dtypes: float64(52), object(1)
memory usage: 980.0+ bytes

In [ ]:
# Extract rows for '15 to 19 years' and '20 to 24 years'
df_15_19 = df_age_percentages[df_age_percentages['Label (Grouping)'] == '15 to 19 years'].drop(columns=['Label (Grouping)']).iloc[0]
df_20_24 = df_age_percentages[df_age_percentages['Label (Grouping)'] == '20 to 24 years'].drop(columns=['Label (Grouping)']).iloc[0]

# Sum the percentages for '15 to 19 years' and '20 to 24 years' for each state
df_combined_age_percentages = pd.DataFrame({
    'State': df_15_19.index,
    'Percentage_15_24': df_15_19.astype(float) + df_20_24.astype(float)
}).reset_index(drop=True)

non_state_entries = ['United States', 'Puerto Rico']
df_age_demographics_cleaned = df_combined_age_percentages[~df_combined_age_percentages['State'].isin(non_state_entries)].copy()

# Ensure 'State' column is clean (e.g., remove leading/trailing spaces if any)
df_age_demographics_cleaned['State'] = df_age_demographics_cleaned['State'].str.strip()

print("Head of Cleaned Age Demographics Data (15-24%):")
display(df_age_demographics_cleaned.head())
print("\nInfo of Cleaned Age Demographics Data (15-24%):")
df_age_demographics_cleaned.info()

Head of Cleaned Age Demographics Data (15-24%):

        State  Percentage_15_24
0     Alabama              14.2
1      Alaska              14.4
2     Arizona              14.3
3    Arkansas              14.2
4  California              14.2

Info of Cleaned Age Demographics Data (15-24%):
<class 'pandas.core.frame.DataFrame'>
Index: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             51 non-null     object
 1   Percentage_15_24  51 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.2+ KB

## Finalize Tobacco Consumption Data

### Subtask:
Теперь, когда `df_tobacco_consumption_filtered_years` содержит данные только за 1975, 1980 и 1988 годы, рассчитайте среднее значение `Cigarette_Packs_Per_Capita` для каждого `State` за эти годы, сохранив результат в DataFrame `df_average_tobacco_consumption`. Отобразите первые строки и информацию о новом DataFrame.

In [ ]:
df_average_tobacco_consumption = df_tobacco_consumption_filtered_years.groupby('State')['Cigarette_Packs_Per_Capita'].mean().reset_index()

print("Average Tobacco Consumption Per State (1975, 1980, 1988):")
display(df_average_tobacco_consumption.head())

print("\nInfo of Average Tobacco Consumption Per State (1975, 1980, 1988):")
df_average_tobacco_consumption.info()

Average Tobacco Consumption Per State (1975, 1980, 1988):

        State  Cigarette_Packs_Per_Capita
0     Alabama                  115.666667
1      Alaska                  121.466667
2     Arizona                  116.933333
3    Arkansas                  122.700000
4  California                  112.466667

Info of Average Tobacco Consumption Per State (1975, 1980, 1988):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   State                       51 non-null     object
 1   Cigarette_Packs_Per_Capita  51 non-null     float64
dtypes: float64(1), object(1)
memory usage: 948.0+ bytes

## Merge All Prepared DataFrames

### Subtask:
Объедините все подготовленные и усредненные DataFrame: `df_average_beer_consumption`, `df_average_gdp`, `df_average_tobacco_consumption`, `df_average_cigarette_price` и `df_age_demographics_cleaned` в один общий DataFrame, используя столбец 'State' в качестве ключа. Отобразите первые строки и информацию об итоговом объединенном DataFrame.

In [ ]:
# Pivot df_tobacco_consumption_filtered_years to get separate columns for each year
df_tobacco_consumption_yearly = df_tobacco_consumption_filtered_years.pivot(index='State', columns='Year', values='Cigarette_Packs_Per_Capita').reset_index()

# Rename columns for clarity
df_tobacco_consumption_yearly.columns = ['State', 'Cigarette_Packs_Per_Capita_1975', 'Cigarette_Packs_Per_Capita_1980', 'Cigarette_Packs_Per_Capita_1988']

print("Yearly Tobacco Consumption Per State (1975, 1980, 1988):")
display(df_tobacco_consumption_yearly.head())

print("\nInfo of Yearly Tobacco Consumption Per State (1975, 1980, 1988):")
df_tobacco_consumption_yearly.info()

Yearly Tobacco Consumption Per State (1975, 1980, 1988):

,State,Cigarette_Packs_Per_Capita_1975,Cigarette_Packs_Per_Capita_1980,Cigarette_Packs_Per_Capita_1988
0,Alabama,111.7,123.2,112.1
1,Alaska,150.4,134.0,80.0
2,Arizona,121.8,126.8,102.2
3,Arkansas,114.8,131.8,121.5
4,California,127.1,120.2,90.1

Info of Yearly Tobacco Consumption Per State (1975, 1980, 1988):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 4 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   State                            51 non-null     object
 1   Cigarette_Packs_Per_Capita_1975  51 non-null     float64
 2   Cigarette_Packs_Per_Capita_1980  51 non-null     float64
 3   Cigarette_Packs_Per_Capita_1988  51 non-null     float64
dtypes: float64(3), object(1)
memory usage: 1.7+ KB

### Subtask:
Обновите процесс объединения, чтобы использовать `df_tobacco_consumption_yearly` вместо `df_average_tobacco_consumption`.

In [ ]:
from functools import reduce

data_frames = [
    df_average_beer_consumption,
    df_average_gdp,
    df_tobacco_consumption_yearly,  # Changed from df_average_tobacco_consumption
    df_average_cigarette_price,
    df_age_demographics_cleaned
]

df_merged_final = reduce(lambda left, right: pd.merge(left, right, on='State', how='inner'), data_frames)

# List of states to exclude
excluded_states = [
    'Alaska', 'Hawaii', 'Maryland', 'Michigan', 'New Jersey',
    'New York', 'Washington', 'Massachusetts', 'Arizona', 'Oregon', 'Florida'
]

# Filter out the excluded states
df_merged_final = df_merged_final[~df_merged_final['State'].isin(excluded_states)].copy()

print("Head of Final Merged DataFrame (Excluded States):")
display(df_merged_final.head())

print("\nInfo of Final Merged DataFrame (Excluded States):")
df_merged_final.info()

Head of Final Merged DataFrame (Excluded States):

,State,Beer_Consumption_Per_Capita,GDP_Per_Capita,Cigarette_Packs_Per_Capita_1975,Cigarette_Packs_Per_Capita_1980,Cigarette_Packs_Per_Capita_1988,Average_Cigarette_Price,Percentage_15_24
0,Alabama,1.086,9664.666667,111.7,123.2,112.1,96.200000,14.2
1,Arkansas,1.066,9313.222222,114.8,131.8,121.5,97.233333,14.2
2,California,1.342,13826.888889,127.1,120.2,90.1,96.566667,14.2
3,Colorado,1.474,12905.555556,131.0,131.0,94.6,91.088889,14.2
4,Connecticut,1.118,15211.888889,110.2,118.0,104.8,111.811111,11.9

Info of Final Merged DataFrame (Excluded States):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   State                            39 non-null     object
 1   Beer_Consumption_Per_Capita      39 non-null     float64
 2   GDP_Per_Capita                   39 non-null     float64
 3   Cigarette_Packs_Per_Capita_1975  39 non-null     float64
 4   Cigarette_Packs_Per_Capita_1980  39 non-null     float64
 5   Cigarette_Packs_Per_Capita_1988  39 non-null     float64
 6   Average_Cigarette_Price          39 non-null     float64
 7   Percentage_15_24                 39 non-null     float64
dtypes: float64(7), object(1)
memory usage: 2.6+ KB

## Сохранение финальной объединенной таблицы в CSV

### Задание:
Сохраните `df_merged_final` в CSV-файл с именем `final_merged_data.csv` в папку `data_folder_path`.

In [ ]:
output_csv_path = os.path.join(data_folder_path, 'final_merged_data.csv')
df_merged_final.to_csv(output_csv_path, index=False)
print(f"Финальная объединенная таблица успешно сохранена в: {output_csv_path}")

Финальная объединенная таблица успешно сохранена в: /content/drive/MyDrive/КурсоваяСинтетическийКонтроль/dataFiles/final_merged_data.csv

Следующая ячейка готовит данные по подушевому потреблению сигарет в 39 штатах(вместе с калифорнией) за 1970-2004

In [5]:
df_cigarette_consumption_all_years = df_tobacco_raw[
    df_tobacco_raw['SubMeasureDesc'] == 'Cigarette Consumption (Pack Sales Per Capita)'
].copy()

df_cigarette_consumption_all_years = df_cigarette_consumption_all_years[[
    'LocationDesc', 'Year', 'Data_Value'
]]

df_cigarette_consumption_all_years.rename(columns={
    'LocationDesc': 'State',
    'Year': 'Year',
    'Data_Value': 'Cigarette_Packs_Per_Capita'
}, inplace=True)

# Clean 'Cigarette_Packs_Per_Capita' column: remove commas and convert to numeric
df_cigarette_consumption_all_years['Cigarette_Packs_Per_Capita'] = df_cigarette_consumption_all_years['Cigarette_Packs_Per_Capita'].str.replace(',', '.', regex=False)
df_cigarette_consumption_all_years['Cigarette_Packs_Per_Capita'] = pd.to_numeric(df_cigarette_consumption_all_years['Cigarette_Packs_Per_Capita'], errors='coerce')

# Filter for years 1970 to 2004
df_filtered_by_years = df_cigarette_consumption_all_years[
    (df_cigarette_consumption_all_years['Year'] >= 1970) &
    (df_cigarette_consumption_all_years['Year'] <= 2004)
].copy()

# List of states to exclude
excluded_states = [
    'Alaska', 'Hawaii', 'Maryland', 'Michigan', 'New Jersey',
    'New York', 'Washington', 'Massachusetts', 'Arizona', 'Oregon',
    'Florida', 'District of Columbia'
]

# Filter out the excluded states
df_cigarette_consumption_39_states = df_filtered_by_years[~df_filtered_by_years['State'].isin(excluded_states)].copy()

print("Head of Cigarette Packs Per Capita for 39 States (1970-2004):")
display(df_cigarette_consumption_39_states.head())

print("\nInfo of Cigarette Packs Per Capita for 39 States (1970-2004):")
df_cigarette_consumption_39_states.info()

# Define the output path for the new CSV file
output_csv_path_39_states = os.path.join(data_folder_path, 'Cigarette_packs_per_capita_39_states_1970_2004.csv')

# Save the DataFrame to CSV
df_cigarette_consumption_39_states.to_csv(output_csv_path_39_states, index=False)

print(f"\nDataFrame успешно сохранен в: {output_csv_path_39_states}")

Head of Cigarette Packs Per Capita for 39 States (1970-2004):

          State  Year  Cigarette_Packs_Per_Capita
1       Alabama  2004                        87.9
7      Arkansas  2004                        79.8
9    California  2004                        33.1
11     Colorado  2004                        60.7
13  Connecticut  2004                        53.1

Info of Cigarette Packs Per Capita for 39 States (1970-2004):
<class 'pandas.core.frame.DataFrame'>
Index: 1365 entries, 1 to 3569
Data columns (total 3 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   State                       1365 non-null   object
 1   Year                        1365 non-null   int64
 2   Cigarette_Packs_Per_Capita  1365 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 42.7+ KB

DataFrame успешно сохранен в: /content/drive/MyDrive/КурсоваяСинтетическийКонтроль/dataFiles/Cigarette_packs_per_capita_39_states_1970_2004.csv